-- Phase 2 planning schema. This is a starting point for Supabase.
create table if not exists profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  designation text,
  department text,
  institution text,
  address text,
  email text,
  bio text,
  photo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  pdf_url text,
  published boolean default false,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists scholars (
  id bigint generated by default as identity primary key,
  name text not null,
  topic text,
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists publications (
  id bigint generated by default as identity primary key,
  title text not null,
  venue text,
  year int,
  doi text,
  type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  image_url text,
  published boolean default false,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  title text not null,
  file_url text,
  category text,
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists routine (
  id bigint generated by default as identity primary key,
  day_name text,
  course_name text,
  time_text text,
  room text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table profiles enable row level security;
alter table notices enable row level security;
alter table scholars enable row level security;
alter table publications enable row level security;
alter table news enable row level security;
alter table resources enable row level security;
alter table routine enable row level security;
